import type { Metadata } from "next";
import "./globals.css";
import Inter, { Inter_Tight } from "next/font/google";
import { Navbar } from "./page";

const inter = Inter_Tight({
  weight: ["400", "500", "600", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "QR Apparel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />

      <body className={`${inter.className} antialiased h-screen`}>
        {children}
      </body>
    </html>
  );
}
